apiVersion: v1
kind: Service
metadata:
  name: charlie-service-processor
spec:
  selector:
    app: charlie-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: my-container
    image: "my-image:latest"
    env:
      - name: GCP_KEY_TEMP
        value: "E2C4F43C867C924D2FA9EE73468F8" # Temporary key
